[2015-01-11 21:42:27.272]	[hhqcs.setup.SetupDataManager] setup könyvtár helye: D:\dropbox\Dropbox\javaprog\HHQCS\setup
[2015-01-11 21:42:31.702]	[hhqcs.sql.SQL] minadat_ID(1) Hiba történt az adatbázis kapcsolódása közben:
								org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:225)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:138)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:410)
	at org.postgresql.Driver.connect(Driver.java:280)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at hhqcs.sql.SQL.minadat_ID(SQL.java:56)
	at hhqcs.setup.SetupDataManager.init(SetupDataManager.java:215)
	at hhqcs.HHQCS.main(HHQCS.java:45)
Caused by: java.net.UnknownHostException: allasido.dunaferr.hu
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 13 more

[2015-01-11 21:42:31.702]	[hhqcs.setup.SetupDataManager] SetupDataManager.init(): Hiba történt a D:\dropbox\Dropbox\javaprog\HHQCS\setup\setup_01.xml beállítási könyvtár feldolgozása közben:
								hibás Plant ID:1 Nem található az Id -hoz tartozó berendezés az adatbázisban
[2015-01-11 21:42:35.415]	[hhqcs.sql.SQL] minadat_ID(2) Hiba történt az adatbázis kapcsolódása közben:
								org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:225)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:138)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:410)
	at org.postgresql.Driver.connect(Driver.java:280)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at hhqcs.sql.SQL.minadat_ID(SQL.java:56)
	at hhqcs.setup.SetupDataManager.init(SetupDataManager.java:215)
	at hhqcs.HHQCS.main(HHQCS.java:45)
Caused by: java.net.UnknownHostException: allasido.dunaferr.hu
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 13 more

[2015-01-11 21:42:35.415]	[hhqcs.setup.SetupDataManager] SetupDataManager.init(): Hiba történt a D:\dropbox\Dropbox\javaprog\HHQCS\setup\setup_02.xml beállítási könyvtár feldolgozása közben:
								hibás Plant ID:2 Nem található az Id -hoz tartozó berendezés az adatbázisban
[2015-01-11 21:42:40.001]	[hhqcs.sql.SQL] minadat_ID(3) Hiba történt az adatbázis kapcsolódása közben:
								org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:225)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:138)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:410)
	at org.postgresql.Driver.connect(Driver.java:280)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at hhqcs.sql.SQL.minadat_ID(SQL.java:56)
	at hhqcs.setup.SetupDataManager.init(SetupDataManager.java:215)
	at hhqcs.HHQCS.main(HHQCS.java:45)
Caused by: java.net.UnknownHostException: allasido.dunaferr.hu
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 13 more

[2015-01-11 21:42:40.001]	[hhqcs.setup.SetupDataManager] SetupDataManager.init(): Hiba történt a D:\dropbox\Dropbox\javaprog\HHQCS\setup\setup_03.xml beállítási könyvtár feldolgozása közben:
								hibás Plant ID:3 Nem található az Id -hoz tartozó berendezés az adatbázisban
